#!/bin/bash
#############################################################################
DOTFILES_HOME="${1:-$HOME/.dotfiles}"
REPOS_HOME="${2:-$DOTFILES_HOME/repos}"

#############################################################################
# Installs the dotfiles.  Execute and then source .bash_profile

install () {
  grep -v DOTFILES_HOME "$1" > "$1.tmp" 2>/dev/null
  cat - "$1.tmp" > "$1"
  rm "$1.tmp"
}

install ~/.bash_profile <<DOC
export DOTFILES_HOME="$DOTFILES_HOME"
source "\$DOTFILES_HOME/files/bash_profile"
DOC

install ~/.vimrc <<"DOC"
source $DOTFILES_HOME/files/vimrc
DOC

#############################################################################
# Setup git
if which -s git 
then git config --global color.ui true
fi

#############################################################################
# Setup scripts 
git_clone () {
  if ! [ -d "$(basename "$1" ".git")" ]
  then git clone "$1"
  fi
}

if [ -e "$DOTFILES_HOME/repos" ] && ! rm "$DOTFILES_HOME/repos"
then
  printf "Manually remove the repos dir and try again.\n"
  exit 1
fi

mkdir -p "$REPOS_HOME"
if ! [ -e "$DOTFILES_HOME/repos" ]
then ln -s "$REPOS_HOME" "$DOTFILES_HOME/repos"
fi
cd "$REPOS_HOME"

git_clone git://gist.github.com/2638925.git 
git_clone git://github.com/thinkerbot/ts.git

cd - >/dev/null

