#!/bin/bash
#############################################################################
# Installs the dotfiles.  Execute and then source .bash_profile

install () {
  grep -v DOTFILES_HOME "$1" > "$1.tmp" 2>/dev/null
  cat - "$1.tmp" > "$1"
  rm "$1.tmp"
}

DOTFILES_HOME="${1:-$HOME/.dotfiles}"

install ~/.bash_profile <<DOC
export DOTFILES_HOME="$DOTFILES_HOME"
source "\$DOTFILES_HOME/files/bash_profile"
DOC

install ~/.vimrc <<"DOC"
source $DOTFILES_HOME/files/vimrc
DOC

#############################################################################
# Setup git
if which -s git 
then git config --global color.ui true
fi

#############################################################################
# Setup scripts 
git_clone () {
  if ! [ -d "$(basename "$1" ".git")" ]
  then git clone "$1"
  fi
}

repos_dir="$DOTFILES_HOME/repos"
mkdir -p "$repos_dir"
cd "$repos_dir"

git_clone git://gist.github.com/2638925.git 
git_clone git://github.com/thinkerbot/ts.git

cd - >/dev/null

