"" Settings
set nocompatible
set backspace=indent,eol,start
set number
set hidden
set ruler

"" Indent settings
set shiftwidth=2
set expandtab
set autoindent

"" Searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"" Usability
if has("syntax")
  syntax on                     "turn on syntax highlighting
endif

if has("mouse")
  set mouse=a                   "enable the mouse
endif

